### ISSUE TITLE
FastAsyncVoxelSniper - Paper 1.14.4

### ISSUE THREAD

**Issue by BenjaminHoegh** [IntellectualSites/FastAsyncVoxelSniper-Legacy#7]
```
02.09 20:23:29 [Server] INFO Ranazomic issued server command: /b e smooth
02.09 20:23:29 [Server] WARN java.lang.ClassNotFoundException: com.martiansoftware.jsap.JSAPException
02.09 20:23:29 [Server] WARN at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
02.09 20:23:29 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139)
02.09 20:23:29 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
02.09 20:23:29 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
02.09 20:23:29 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
02.09 20:23:29 [Server] WARN at java.lang.Class.getDeclaredConstructors0(Native Method)
02.09 20:23:29 [Server] WARN at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
02.09 20:23:29 [Server] WARN at java.lang.Class.getConstructor0(Class.java:3075)
02.09 20:23:29 [Server] WARN at java.lang.Class.newInstance(Class.java:412)
02.09 20:23:29 [Server] WARN at com.thevoxelbox.voxelsniper.Sniper$SniperTool.instantiateBrush(Sniper.java:646)
02.09 20:23:29 [Server] WARN at com.thevoxelbox.voxelsniper.Sniper$SniperTool.setCurrentBrush(Sniper.java:618)
02.09 20:23:29 [Server] WARN at com.thevoxelbox.voxelsniper.Sniper.setBrush(Sniper.java:436)
02.09 20:23:29 [Server] WARN at com.thevoxelbox.voxelsniper.command.VoxelBrushCommand.onCommand(VoxelBrushCommand.java:52)
02.09 20:23:29 [Server] WARN at com.thevoxelbox.voxelsniper.VoxelSniperListener.lambda$onCommand$0(VoxelSniperListener.java:77)
02.09 20:23:29 [Server] WARN at com.boydti.fawe.object.FawePlayer.lambda$runAction$4(FawePlayer.java:314)
02.09 20:23:29 [Server] WARN at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25)
02.09 20:23:29 [Server] WARN at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15)
02.09 20:23:29 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
02.09 20:23:29 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
02.09 20:23:29 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
02.09 20:23:29 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02.09 20:23:29 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
02.09 20:23:29 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

 - PaperSpigot 1.14.4
 - Plugins:
   - FastAsyncWorldEdit
   - FastAsyncVoxelsniper
   - WorldGuard
  - Default config

**Comment by Cjen1** [comment]
Just to give a +1 to this. It only seems to occur on `\b e ...`
