### ISSUE TITLE
b e melt command error

### ISSUE THREAD

**Issue by ArmyAgira** [IntellectualSites/FastAsyncVoxelSniper-Legacy#8]
# Bug report for FastAsyncVoxelSniper 1.13.2+

**[REQUIRED] FastAsyncWorldEdit Version Number: 1.14-37** 

**[REQUIRED] Spigot/Paper Version Number: 1.14.4-R0.1-SNAPSHOT** 

**Links to config.yml and config-legacy.yml file:** https://pastebin.com/wyrb6Da8
https://pastebin.com/MRpH04u4

**[REQUIRED] Description of the problem:**

[20:39:53 INFO]: Army_Agira issued server command: /b e melt 2
[20:39:53 WARN]: java.lang.ClassNotFoundException: com.martiansoftware.jsap.JSAPException
[20:39:53 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[20:39:53 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139)
[20:39:53 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
[20:39:53 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[20:39:53 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[20:39:53 WARN]:        at java.lang.Class.getDeclaredConstructors0(Native Method)
[20:39:53 WARN]:        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
[20:39:53 WARN]:        at java.lang.Class.getConstructor0(Unknown Source)
[20:39:53 WARN]:        at java.lang.Class.newInstance(Unknown Source)
[20:39:53 WARN]:        at com.thevoxelbox.voxelsniper.Sniper$SniperTool.instantiateBrush(Sniper.java:646)
[20:39:53 WARN]:        at com.thevoxelbox.voxelsniper.Sniper$SniperTool.setCurrentBrush(Sniper.java:618)
[20:39:53 WARN]:        at com.thevoxelbox.voxelsniper.Sniper.setBrush(Sniper.java:436)
[20:39:53 WARN]:        at com.thevoxelbox.voxelsniper.command.VoxelBrushCommand.onCommand(VoxelBrushCommand.java:52)
[20:39:53 WARN]:        at com.thevoxelbox.voxelsniper.VoxelSniperListener.lambda$onCommand$0(VoxelSniperListener.java:77)
[20:39:53 WARN]:        at com.boydti.fawe.object.FawePlayer.lambda$runAction$4(FawePlayer.java:314)
[20:39:53 WARN]:        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25)
[20:39:53 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15)
[20:39:53 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[20:39:53 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[20:39:53 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:39:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:39:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:39:53 WARN]:        at java.lang.Thread.run(Unknown Source)

**Plugins being used on the server:**

https://pasteboard.co/IBtg3xX.png
**How to replicate**:

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncVoxelSniper/issues)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit & FastAsyncVoxelSniper](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by NotMyFault** [comment]
Duplicate of https://github.com/IntellectualSites/FastAsyncVoxelSniper/issues/7
